# Generated by cucumber-sinatra. (2014-01-13 12:28:36 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'etiquetica.rb')

require 'capybara'
require 'capybara-webkit'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Etiquetica
Capybara.default_driver = :webkit
Capybara.javascript_driver = :webkit
Capybara.default_wait_time = 5

class EtiqueticaWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  EtiqueticaWorld.new
end
